import { DEFAULT_MAINTENANCE_OFFER } from "@/lib/proposals/maintenance";
import { fireEvent, render, screen, waitFor } from "@testing-library/react";
import { beforeEach, describe, expect, it, vi } from "vitest";

vi.mock("@/components/finance/line-items-table", () => ({ LineItemsTable: () => null }));
vi.mock("@/components/proposals/maintenance-offer-editor", () => ({
  MaintenanceOfferEditor: () => null,
}));
vi.mock("@/components/proposals/problem-solution-editor", () => ({
  ProblemSolutionEditor: () => null,
}));
vi.mock("@/components/proposals/scope-modules-editor", () => ({ ScopeModulesEditor: () => null }));
vi.mock("../actions", () => ({ updateProposal: vi.fn() }));

import { updateProposal } from "../actions";
import { ProposalEditor } from "./proposal-editor";

const ID = "494d62cb-fd56-4650-b131-9e3a927a20ad";
const saveProposal = vi.mocked(updateProposal);
const props = {
  id: ID,
  initialTitle: "Propuesta inicial",
  initialValidUntil: null,
  initialNotes: null,
  initialContextMarkdown: null,
  initialProblems: [],
  initialSolutions: [],
  initialTerms: null,
  initialScopeModules: [],
  initialDeliverables: null,
  initialAcceptanceCriteria: null,
  initialPaymentSchedule: null,
  initialPaymentTerms: null,
  initialChangeManagementTerms: null,
  initialMaintenanceOptions: DEFAULT_MAINTENANCE_OFFER,
  initialMaintenanceSelectedPlanId: null,
  initialItems: [],
  initialVersion: 1,
  locked: false,
  aiEnabled: false,
  leadId: null,
  autoGenerateDraft: false,
};

describe("ProposalEditor", () => {
  beforeEach(() => {
    saveProposal.mockReset();
    saveProposal.mockResolvedValue({ ok: true, version: 2 });
  });

  it("only saves proposal edits when the user presses Guardar cambios", async () => {
    render(<ProposalEditor {...props} />);

    fireEvent.change(screen.getByLabelText("Título"), { target: { value: "Propuesta revisada" } });
    expect(saveProposal).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole("button", { name: "Guardar" }));

    await waitFor(() =>
      expect(saveProposal).toHaveBeenCalledWith(
        expect.objectContaining({ id: ID, title: "Propuesta revisada" }),
      ),
    );
  });

  it("guides the user through the proposal steps", () => {
    render(<ProposalEditor {...props} />);

    expect(screen.getByRole("heading", { name: "Empieza por lo esencial" })).toBeDefined();
    fireEvent.click(screen.getByRole("button", { name: "Continuar a Alcance" }));
    expect(screen.getByRole("heading", { name: "Cuenta la propuesta" })).toBeDefined();

    fireEvent.click(screen.getByRole("button", { name: "Continuar a Precio" }));
    expect(screen.getByRole("heading", { name: "Precio de la propuesta" })).toBeDefined();
  });
});
