import type { AttachmentItem } from '@/components/ui/attachment-section'
import type { LineItem as EditableItem } from '@/lib/finance'
import type { EditableKeyPoint } from '@/lib/proposals/key-points'
import type { MaintenanceOffer } from '@/lib/proposals/maintenance'
import type { PaymentPlanItem, PaymentSchedule, ScopeModule } from '@/lib/proposals/scope'

type ProposalTeamMember = { id: string; name: string; job_title: string | null }

export type ProposalEditorProps = {
  id: string
  initialTitle: string
  initialValidUntil: string | null
  initialNotes: string | null
  initialContextMarkdown: string | null
  initialProblems: EditableKeyPoint[]
  initialSolutions: EditableKeyPoint[]
  initialTerms: string | null
  initialScopeModules: ScopeModule[]
  initialDeliverables: string | null
  initialAcceptanceCriteria: string | null
  initialPaymentSchedule: PaymentSchedule | null
  initialPaymentPlan: PaymentPlanItem[]
  initialPaymentTerms: string | null
  initialChangeManagementTerms: string | null
  initialLegalTerms?: string | null
  initialMaintenanceOptions: MaintenanceOffer | null
  initialMaintenanceSelectedPlanId: string | null
  teamMembers: ProposalTeamMember[]
  initialTeamMemberIds: string[]
  initialItems: EditableItem[]
  initialCreatedAt?: string | null
  initialAttachments: AttachmentItem[]
  /** Optimistic-concurrency token captured with the record. */
  initialVersion: number
  /** When true, fields are read-only (proposal accepted/rejected). */
  locked: boolean
  /** Gates the "generate problems/solutions with AI" affordance. */
  aiEnabled: boolean
  /** The lead whose CRM briefing can be used to prepare this proposal. */
  leadId: string | null
  /** Runs once when arriving from the "Crear y prerrellenar" flow. */
  autoGenerateDraft: boolean
}
