"use client";

import { AlertCircle } from "lucide-react";
import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { LineItemsTable } from "@/components/finance/line-items-table";
import { ProblemSolutionEditor } from "@/components/proposals/problem-solution-editor";
import { ScopeModulesEditor } from "@/components/proposals/scope-modules-editor";
import { AiNotice } from "@/components/ui/ai-notice";
import { Alert, AlertDescription, AlertTitle } from "@/components/ui/alert";
import { AutosaveIndicator } from "@/components/ui/autosave-indicator";
import { Button } from "@/components/ui/button";
import { FormFeedback, useFormFeedback } from "@/components/ui/form-feedback";
import { FormRow } from "@/components/ui/form-row";
import { Input } from "@/components/ui/input";
import { Markdown } from "@/components/ui/markdown";
import { Select } from "@/components/ui/select";
import { Textarea } from "@/components/ui/textarea";
import { EMPTY_LINE_ITEM, type LineItem } from "@/lib/finance";
import { useAutosave } from "@/lib/hooks/use-autosave";
import {
  createEmptyPair,
  type EditableKeyPoint,
  type EditablePair,
  serializeKeyPoints,
  unzipPairs,
  zipKeyPoints,
} from "@/lib/proposals/key-points";
import {
  DEFAULT_CHANGE_MANAGEMENT_TERMS,
  PAYMENT_SCHEDULE_LABELS,
  PAYMENT_SCHEDULE_TEMPLATES,
  type PaymentSchedule,
  type ScopeModule,
} from "@/lib/proposals/scope";
import { updateProposal } from "../actions";

export type EditableItem = LineItem;

export type ProposalEditorProps = {
  id: string;
  initialTitle: string;
  initialValidUntil: string | null;
  initialNotes: string | null;
  initialContextMarkdown: string | null;
  initialProblems: EditableKeyPoint[];
  initialSolutions: EditableKeyPoint[];
  initialTerms: string | null;
  initialScopeModules: ScopeModule[];
  initialDeliverables: string | null;
  initialAcceptanceCriteria: string | null;
  initialPaymentSchedule: PaymentSchedule | null;
  initialPaymentTerms: string | null;
  initialChangeManagementTerms: string | null;
  initialItems: EditableItem[];
  /** When true, fields are read-only (proposal accepted/rejected). */
  locked: boolean;
  /** Gates the "generate problems/solutions with AI" affordance. */
  aiEnabled: boolean;
  /** The lead whose CRM briefing can be used to prepare this proposal. */
  leadId: string | null;
  /** Runs once when arriving from the "Crear y prerrellenar" flow. */
  autoGenerateDraft: boolean;
};

/**
 * Inline editor for the proposal detail page. Every field autosaves with a
 * 2 s debounce via `updateProposal` server action so two team members can
 * collaborate without explicit save buttons.
 *
 * Narrative is split into three blocks (context / problems / solutions) that
 * map 1-to-1 to deck slides and portal sections; see
 * `lib/proposals/key-points.ts` for the wire shape.
 */
export function ProposalEditor({
  id,
  initialTitle,
  initialValidUntil,
  initialNotes,
  initialContextMarkdown,
  initialProblems,
  initialSolutions,
  initialTerms,
  initialScopeModules,
  initialDeliverables,
  initialAcceptanceCriteria,
  initialPaymentSchedule,
  initialPaymentTerms,
  initialChangeManagementTerms,
  initialItems,
  locked,
  aiEnabled,
  leadId,
  autoGenerateDraft,
}: ProposalEditorProps) {
  const [title, setTitle] = useState(initialTitle);
  const [validUntil, setValidUntil] = useState(initialValidUntil ?? "");
  const [notes, setNotes] = useState(initialNotes ?? "");
  const [notesPreview, setNotesPreview] = useState(false);
  const [contextMarkdown, setContextMarkdown] = useState(initialContextMarkdown ?? "");
  const [pairs, setPairs] = useState<EditablePair[]>(() =>
    zipKeyPoints(initialProblems, initialSolutions),
  );
  const [generating, setGenerating] = useState(false);
  const aiFeedback = useFormFeedback();
  const automaticDraftStarted = useRef(false);
  const [terms, setTerms] = useState(initialTerms ?? "");
  const [scopeModules, setScopeModules] = useState(initialScopeModules);
  const [deliverables, setDeliverables] = useState(initialDeliverables ?? "");
  const [acceptanceCriteria, setAcceptanceCriteria] = useState(initialAcceptanceCriteria ?? "");
  const [paymentSchedule, setPaymentSchedule] = useState<PaymentSchedule>(
    initialPaymentSchedule ?? "half_half",
  );
  const [paymentTerms, setPaymentTerms] = useState(
    initialPaymentTerms ?? PAYMENT_SCHEDULE_TEMPLATES.half_half,
  );
  const [changeManagementTerms, setChangeManagementTerms] = useState(
    initialChangeManagementTerms ?? DEFAULT_CHANGE_MANAGEMENT_TERMS,
  );
  const [items, setItems] = useState<EditableItem[]>(
    initialItems.length > 0
      ? initialItems.map((it) => ({ ...it, id: it.id || crypto.randomUUID() }))
      : [{ ...EMPTY_LINE_ITEM, id: crypto.randomUUID() } as EditableItem],
  );

  const payload = useMemo(() => {
    const { problems, solutions } = unzipPairs(pairs);
    return {
      id,
      title,
      valid_until: validUntil || null,
      notes: notes || null,
      context_markdown: contextMarkdown || null,
      problems: serializeKeyPoints(problems),
      solutions: serializeKeyPoints(solutions),
      terms: terms || null,
      scope_modules: scopeModules.length > 0 ? scopeModules : null,
      deliverables: deliverables || null,
      acceptance_criteria: acceptanceCriteria || null,
      payment_schedule: paymentSchedule,
      payment_terms: paymentTerms || null,
      change_management_terms: changeManagementTerms || null,
      items,
    };
  }, [
    id,
    title,
    validUntil,
    notes,
    contextMarkdown,
    pairs,
    terms,
    scopeModules,
    deliverables,
    acceptanceCriteria,
    paymentSchedule,
    paymentTerms,
    changeManagementTerms,
    items,
  ]);

  const autosave = useAutosave({
    data: payload,
    enabled: !locked,
    storageKey: `proposal-edit:${id}`,
    onSaveAction: async (data) => {
      const res = await updateProposal(data);
      if (!res.ok) return { error: res.error };
    },
  });

  async function handleGenerateNarrative() {
    setGenerating(true);
    aiFeedback.setPending();
    try {
      const res = await fetch(`/api/proposals/${id}/generate-narrative`, { method: "POST" });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "No se pudo generar la narrativa.");
      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, "id">>;
      setPairs(incoming.map((p) => ({ ...createEmptyPair(), ...p })));
      aiFeedback.setSuccess("Narrativa generada");
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : "Error desconocido");
    } finally {
      setGenerating(false);
    }
  }

  const narrativeIsEmpty =
    !notes.trim() && !contextMarkdown.trim() && pairs.length === 0 && !terms.trim();
  const commercialScopeIsEmpty =
    scopeModules.length === 0 && !deliverables.trim() && !acceptanceCriteria.trim();
  const hasEmptyDraftFields =
    narrativeIsEmpty ||
    commercialScopeIsEmpty ||
    !paymentTerms.trim() ||
    !changeManagementTerms.trim();
  const saveErrors = autosave.error?.split("\n").filter(Boolean) ?? [];

  function handlePaymentScheduleChange(value: PaymentSchedule) {
    setPaymentSchedule(value);
    if (value !== "custom") setPaymentTerms(PAYMENT_SCHEDULE_TEMPLATES[value]);
  }

  const handleGenerateDraft = useCallback(async () => {
    if (!leadId || generating || locked || !hasEmptyDraftFields) return;
    setGenerating(true);
    aiFeedback.setPending();
    try {
      const res = await fetch(`/api/proposals/${id}/generate-draft`, { method: "POST" });
      const json = await res.json();
      if (!res.ok) throw new Error(json.error ?? "No se pudo preparar la propuesta.");

      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, "id">>;
      const nextPairs = incoming.map((pair) => ({ ...createEmptyPair(), ...pair }));
      const nextScopeModules = (json.scope_modules ?? []) as ScopeModule[];
      const titleIsEmpty = !title.trim();
      const notesAreEmpty = !notes.trim();
      const contextIsEmpty = !contextMarkdown.trim();
      const pairsAreEmpty = pairs.length === 0;
      const termsAreEmpty = !terms.trim();
      const modulesAreEmpty = scopeModules.length === 0;
      const deliverablesAreEmpty = !deliverables.trim();
      const acceptanceCriteriaAreEmpty = !acceptanceCriteria.trim();
      const paymentTermsAreEmpty = !paymentTerms.trim();
      const changeManagementTermsAreEmpty = !changeManagementTerms.trim();
      const nextKeyPoints = pairsAreEmpty ? unzipPairs(nextPairs) : null;
      const generatedNarrativePatch = pairsAreEmpty
        ? {
            problems: serializeKeyPoints(nextKeyPoints?.problems ?? []),
            solutions: serializeKeyPoints(nextKeyPoints?.solutions ?? []),
          }
        : {};
      const generatedPaymentTermsPatch = paymentTermsAreEmpty
        ? {
            payment_schedule: json.payment_schedule as PaymentSchedule,
            payment_terms: json.payment_terms || null,
          }
        : {};
      const save = await updateProposal({
        id,
        ...(titleIsEmpty ? { title: json.title } : {}),
        ...(notesAreEmpty ? { notes: json.notes || null } : {}),
        ...(contextIsEmpty ? { context_markdown: json.context_markdown || null } : {}),
        ...generatedNarrativePatch,
        ...(termsAreEmpty ? { terms: json.terms || null } : {}),
        ...(modulesAreEmpty && nextScopeModules.length > 0
          ? { scope_modules: nextScopeModules }
          : {}),
        ...(deliverablesAreEmpty ? { deliverables: json.deliverables || null } : {}),
        ...(acceptanceCriteriaAreEmpty
          ? { acceptance_criteria: json.acceptance_criteria || null }
          : {}),
        ...generatedPaymentTermsPatch,
        ...(changeManagementTermsAreEmpty
          ? { change_management_terms: json.change_management_terms || null }
          : {}),
      });
      if (!save.ok) throw new Error(save.error);

      if (titleIsEmpty) setTitle(json.title);
      if (notesAreEmpty) setNotes(json.notes ?? "");
      if (contextIsEmpty) setContextMarkdown(json.context_markdown ?? "");
      if (pairsAreEmpty) setPairs(nextPairs);
      if (termsAreEmpty) setTerms(json.terms ?? "");
      if (modulesAreEmpty && nextScopeModules.length > 0) setScopeModules(nextScopeModules);
      if (deliverablesAreEmpty) setDeliverables(json.deliverables ?? "");
      if (acceptanceCriteriaAreEmpty) setAcceptanceCriteria(json.acceptance_criteria ?? "");
      if (paymentTermsAreEmpty) {
        setPaymentSchedule(json.payment_schedule as PaymentSchedule);
        setPaymentTerms(json.payment_terms ?? "");
      }
      if (changeManagementTermsAreEmpty) {
        setChangeManagementTerms(json.change_management_terms ?? "");
      }
      aiFeedback.setSuccess("Borrador preparado con el contexto del lead");
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : "Error desconocido");
    } finally {
      setGenerating(false);
    }
  }, [
    acceptanceCriteria,
    aiFeedback,
    changeManagementTerms,
    contextMarkdown,
    deliverables,
    generating,
    hasEmptyDraftFields,
    id,
    leadId,
    locked,
    notes,
    pairs,
    paymentTerms,
    scopeModules,
    terms,
    title,
  ]);

  useEffect(() => {
    if (
      !autoGenerateDraft ||
      !aiEnabled ||
      !leadId ||
      locked ||
      !narrativeIsEmpty ||
      !commercialScopeIsEmpty ||
      automaticDraftStarted.current
    ) {
      return;
    }
    automaticDraftStarted.current = true;
    void handleGenerateDraft();
  }, [
    autoGenerateDraft,
    aiEnabled,
    leadId,
    locked,
    narrativeIsEmpty,
    commercialScopeIsEmpty,
    handleGenerateDraft,
  ]);

  return (
    <div className="flex flex-col gap-4">
      <div className="flex flex-wrap items-center gap-3">
        <Input
          value={title}
          onChange={(e) => setTitle(e.target.value)}
          disabled={locked}
          placeholder="Título de la propuesta"
          className="flex-1 min-w-0 h-9 text-base font-medium"
          aria-label="Título"
        />
        <AutosaveIndicator
          status={autosave.status}
          savedAt={autosave.savedAt}
          error={autosave.error}
        />
        {!locked && (
          <Button
            size="sm"
            variant="outline"
            onClick={autosave.saveNow}
            disabled={autosave.status === "saving"}
          >
            Guardar
          </Button>
        )}
      </div>

      {autosave.status === "error" && saveErrors.length > 0 ? (
        <Alert variant="destructive" className="border-destructive/30 bg-destructive/5 px-4 py-3">
          <AlertCircle className="size-4" aria-hidden />
          <AlertTitle>No se ha podido guardar la propuesta</AlertTitle>
          <AlertDescription>
            <p>Revisa y corrige estos campos. Tus cambios siguen en esta pantalla.</p>
            <ul className="mt-2 list-disc space-y-1 pl-5">
              {saveErrors.map((error) => (
                <li key={error}>{error}</li>
              ))}
            </ul>
          </AlertDescription>
        </Alert>
      ) : null}

      <div className="grid gap-4 lg:grid-cols-[minmax(0,2fr)_minmax(0,1fr)]">
        <div className="min-w-0 overflow-hidden rounded-lg border border-border">
          <LineItemsTable items={items} onChange={setItems} locked={locked} showBillingCycle />
        </div>

        <aside className="flex min-w-0 flex-col gap-3">
          <FormRow label="Válida hasta" htmlFor="valid-until">
            <Input
              id="valid-until"
              type="date"
              value={validUntil ?? ""}
              onChange={(e) => setValidUntil(e.target.value)}
              disabled={locked}
            />
          </FormRow>
          <div className="flex flex-col gap-1">
            <div className="flex items-center justify-between">
              <span className="text-xs font-medium text-muted-foreground">Notas</span>
              {notes && (
                <button
                  type="button"
                  onClick={() => setNotesPreview((p) => !p)}
                  className="text-xs text-muted-foreground hover:text-foreground transition-colors"
                >
                  {notesPreview ? "Editar" : "Previsualizar"}
                </button>
              )}
            </div>
            {notesPreview && notes ? (
              <div className="rounded-md border border-border bg-muted/20 px-3 py-2 min-h-36">
                <Markdown source={notes} />
              </div>
            ) : (
              <Textarea
                id="notes"
                value={notes}
                onChange={(e) => setNotes(e.target.value)}
                disabled={locked}
                rows={6}
                placeholder="Notas internas o para el cliente… (soporta Markdown)"
              />
            )}
          </div>
        </aside>
      </div>

      {/* Narrative blocks — shown before the price on every client surface */}
      <section className="flex flex-col gap-4 rounded-lg border border-border bg-card p-4">
        <header className="flex items-start justify-between gap-3">
          <div className="flex flex-col gap-0.5">
            <h2 className="text-sm font-semibold">Narrativa de la propuesta</h2>
            <p className="text-[11px] text-muted-foreground">
              Contexto, problemas detectados y enfoque de la solución. Se muestran al cliente antes
              del precio en el portal y como diapositivas en la presentación.
            </p>
          </div>
          <div className="flex shrink-0 items-center gap-2">
            <FormFeedback state={aiFeedback.state} pendingLabel="Generando…" />
            {!aiEnabled ? <AiNotice inline /> : null}
          </div>
        </header>

        {aiEnabled && leadId && hasEmptyDraftFields && !locked ? (
          <div className="flex flex-wrap items-center justify-between gap-3 rounded-md border border-primary/20 bg-primary/5 px-3 py-2.5">
            <p className="text-xs text-muted-foreground">
              Usa las notas, llamadas e historial del lead para preparar el contexto, alcance,
              entregables, criterios de aceptación y condiciones. Solo rellenará los campos vacíos;
              revísalo antes de enviarlo.
            </p>
            <Button
              type="button"
              size="sm"
              variant="outline"
              disabled={generating}
              onClick={handleGenerateDraft}
            >
              {generating ? "Preparando…" : "Preparar borrador con IA"}
            </Button>
          </div>
        ) : null}

        <FormRow
          label="Contexto"
          htmlFor="context-markdown"
          hint="Markdown. Sitúa la situación actual del cliente en 2-3 frases."
        >
          <Textarea
            id="context-markdown"
            value={contextMarkdown}
            onChange={(e) => setContextMarkdown(e.target.value)}
            disabled={locked}
            rows={4}
            className="font-mono text-xs"
            placeholder={"Tras nuestras conversaciones, hemos detectado que…"}
          />
        </FormRow>

        <FormRow
          label="Problemas y soluciones"
          htmlFor="problems-solutions"
          hint="Cada problema con la solución que proponemos. Se muestran emparejados al cliente."
        >
          <ProblemSolutionEditor
            items={pairs}
            onChange={setPairs}
            locked={locked}
            aiEnabled={aiEnabled}
            onGenerate={handleGenerateNarrative}
            generating={generating}
          />
        </FormRow>
      </section>

      <section className="flex flex-col gap-4 rounded-lg border border-border bg-card p-4">
        <header className="flex flex-col gap-0.5">
          <h2 className="text-sm font-semibold">Alcance y entregables</h2>
          <p className="text-[11px] text-muted-foreground">
            Define el trabajo incluido por módulo. Esta estructura se mostrará en el deck y el PDF,
            y podrá alimentar el briefing inicial del proyecto.
          </p>
        </header>
        <ScopeModulesEditor modules={scopeModules} onChange={setScopeModules} locked={locked} />
        <div className="grid gap-4 lg:grid-cols-2">
          <FormRow
            label="Entregables"
            htmlFor="deliverables"
            hint="Markdown. Qué recibirá el cliente al finalizar."
          >
            <Textarea
              id="deliverables"
              value={deliverables}
              onChange={(event) => setDeliverables(event.target.value)}
              disabled={locked}
              rows={5}
              className="font-mono text-xs"
              placeholder={
                "- Diseño validado\n- Desarrollo de los módulos acordados\n- Formación y documentación"
              }
            />
          </FormRow>
          <FormRow
            label="Criterios de aceptación"
            htmlFor="acceptance-criteria"
            hint="Markdown. Cómo comprobaremos que el trabajo está entregado."
          >
            <Textarea
              id="acceptance-criteria"
              value={acceptanceCriteria}
              onChange={(event) => setAcceptanceCriteria(event.target.value)}
              disabled={locked}
              rows={5}
              className="font-mono text-xs"
              placeholder={
                "- Los flujos descritos funcionan en producción.\n- El cliente valida los entregables acordados."
              }
            />
          </FormRow>
        </div>
      </section>

      <section className="grid gap-4 rounded-lg border border-border bg-card p-4 lg:grid-cols-2">
        <FormRow
          label="Forma de pago"
          htmlFor="payment-schedule"
          hint="Elige una base y ajusta el texto si hace falta."
        >
          <div className="flex flex-col gap-3">
            <Select
              id="payment-schedule"
              value={paymentSchedule}
              onChange={(event) =>
                handlePaymentScheduleChange(event.target.value as PaymentSchedule)
              }
              disabled={locked}
            >
              {Object.entries(PAYMENT_SCHEDULE_LABELS).map(([value, label]) => (
                <option key={value} value={value}>
                  {label}
                </option>
              ))}
            </Select>
            <Textarea
              value={paymentTerms}
              onChange={(event) => setPaymentTerms(event.target.value)}
              disabled={locked}
              rows={4}
              className="text-sm"
              placeholder="Condiciones de pago"
              aria-label="Condiciones de pago"
            />
          </div>
        </FormRow>
        <FormRow
          label="Gestión de cambios"
          htmlFor="change-management"
          hint="Texto predefinido y editable para proteger el alcance acordado."
        >
          <Textarea
            id="change-management"
            value={changeManagementTerms}
            onChange={(event) => setChangeManagementTerms(event.target.value)}
            disabled={locked}
            rows={6}
            className="text-sm"
          />
        </FormRow>
        <FormRow
          label="Condiciones adicionales"
          htmlFor="terms"
          hint="Markdown. Vigencia, licencias, garantías u otras condiciones."
        >
          <Textarea
            id="terms"
            value={terms}
            onChange={(event) => setTerms(event.target.value)}
            disabled={locked}
            rows={5}
            className="font-mono text-xs"
            placeholder={
              "## Condiciones adicionales\n\n- Vigencia: 30 días.\n- Licencias de terceros no incluidas."
            }
          />
        </FormRow>
      </section>
    </div>
  );
}
