'use client'

import { CircleAlert as AlertCircle, Check, ChevronLeft, ChevronRight, Save } from 'lucide-react'
import { useRouter } from 'next/navigation'
import { type KeyboardEvent, useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { createPortal } from 'react-dom'

import { Alert, AlertDescription, AlertTitle } from '@/components/ui/alert'
import { Button } from '@/components/ui/button'
import { FormFeedback, useFormFeedback } from '@/components/ui/form-feedback'
import { VersionConflictDialog } from '@/components/ui/version-conflict-dialog'
import { computeProposalTotals, type LineItem } from '@/lib/finance'
import { createEmptyPair, type EditablePair } from '@/lib/proposals/key-points'
import { selectedMaintenancePlan } from '@/lib/proposals/maintenance'
import { ensureCalendarYearProration, recurringPaymentTerms } from '@/lib/proposals/recurring'
import {
  PAYMENT_SCHEDULE_TEMPLATES,
  paymentPlanForSchedule,
  type PaymentSchedule,
  type ScopeModule,
} from '@/lib/proposals/scope'
import { formatEUR } from '@/lib/utils'

import { saveProposalEditor } from '../actions'
import { proposalDraftPayload } from './proposal-draft'
import {
  ProposalDetailsSection,
  ProposalPriceSection,
  ProposalReviewSection,
  ProposalScopeSection,
} from './proposal-editor-sections'
import type { ProposalEditorProps } from './proposal-editor-types'
import { useProposalDraft } from './use-proposal-draft'
export type { ProposalEditorProps } from './proposal-editor-types'

export type EditableItem = LineItem

const EDITOR_STEPS = [
  { label: 'Datos', description: 'Base de la propuesta' },
  { label: 'Alcance', description: 'Qué vamos a entregar' },
  { label: 'Precio', description: 'Partidas y condiciones' },
  { label: 'Revisión', description: 'Equipo y comprobación final' },
] as const

/**
 * Inline editor for the proposal detail page. Changes remain local until the
 * user explicitly saves them, avoiding partial or conflicting writes.
 *
 * Narrative is split into three blocks (context / problems / solutions) that
 * map 1-to-1 to deck slides and portal sections; see
 * `lib/proposals/key-points.ts` for the wire shape.
 */
export function ProposalEditor(props: ProposalEditorProps) {
  const {
    id,
    initialCreatedAt,
    teamMembers,
    initialAttachments,
    initialVersion,
    locked,
    aiEnabled,
    leadId,
    autoGenerateDraft,
  } = props
  const { draft, setField } = useProposalDraft(props)
  const {
    title,
    validUntil,
    notes,
    contextMarkdown,
    pairs,
    terms,
    scopeModules,
    deliverables,
    acceptanceCriteria,
    paymentSchedule,
    paymentTerms,
    paymentTermsCustomized,
    changeManagementTerms,
    maintenanceOptions,
    maintenanceSelectedPlanId,
    items,
  } = draft
  const router = useRouter()
  const [expectedVersion, setExpectedVersion] = useState(initialVersion)
  const [conflictOpen, setConflictOpen] = useState(false)

  const [notesPreview, setNotesPreview] = useState(false)

  const [generating, setGenerating] = useState(false)
  const aiFeedback = useFormFeedback()
  const saveFeedback = useFormFeedback({ successResetMs: 4_000 })
  const automaticDraftStarted = useRef(false)

  const [activeStep, setActiveStep] = useState(0)
  const stepTabRefs = useRef<Array<HTMLButtonElement | null>>([])

  function handleItemsChange(nextItems: LineItem[]) {
    const next = ensureCalendarYearProration(nextItems, initialCreatedAt) as EditableItem[]
    setField('items')(next)
    if (!paymentTermsCustomized) {
      setField('paymentTerms')(
        recurringPaymentTerms(next, initialCreatedAt) ??
          PAYMENT_SCHEDULE_TEMPLATES[paymentSchedule === 'custom' ? 'half_half' : paymentSchedule],
      )
    }
  }

  const [actionsSlot, setActionsSlot] = useState<HTMLElement | null>(null)
  useEffect(() => {
    setActionsSlot(document.getElementById('proposal-editor-actions'))
  }, [])

  const payload = proposalDraftPayload(id, expectedVersion, draft)

  async function handleGenerateNarrative() {
    setGenerating(true)
    aiFeedback.setPending()
    try {
      const res = await fetch(`/api/proposals/${id}/generate-narrative`, { method: 'POST' })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'No se pudo generar la narrativa.')
      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, 'id'>>
      setField('pairs')(incoming.map((p) => ({ ...createEmptyPair(), ...p })))
      aiFeedback.setSuccess('Narrativa generada')
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : 'Error desconocido')
    } finally {
      setGenerating(false)
    }
  }

  const narrativeIsEmpty =
    !notes.trim() && !contextMarkdown.trim() && pairs.length === 0 && !terms.trim()
  const commercialScopeIsEmpty =
    scopeModules.length === 0 && !deliverables.trim() && !acceptanceCriteria.trim()
  const hasEmptyDraftFields =
    narrativeIsEmpty ||
    commercialScopeIsEmpty ||
    !paymentTerms.trim() ||
    !changeManagementTerms.trim()
  const saveErrors =
    saveFeedback.state.status === 'error'
      ? saveFeedback.state.message.split('\n').filter(Boolean)
      : []
  const proposalTotals = useMemo(() => computeProposalTotals(items), [items])
  const selectedMaintenance = selectedMaintenancePlan(maintenanceOptions, maintenanceSelectedPlanId)
  const stepComplete = [
    Boolean(title.trim() && validUntil),
    Boolean(contextMarkdown.trim() || pairs.length || scopeModules.length || deliverables.trim()),
    Boolean(items.some((item) => item.description.trim() && Number(item.quantity) > 0)),
    !maintenanceOptions.enabled || Boolean(selectedMaintenance),
  ]
  const currentStep = EDITOR_STEPS[activeStep] ?? EDITOR_STEPS[0]
  const nextStep = EDITOR_STEPS[activeStep + 1] ?? currentStep

  function handleStepKeyDown(event: KeyboardEvent<HTMLButtonElement>, index: number) {
    const lastStepIndex = EDITOR_STEPS.length - 1
    const nextIndex =
      event.key === 'ArrowRight' || event.key === 'ArrowDown'
        ? index === lastStepIndex
          ? 0
          : index + 1
        : event.key === 'ArrowLeft' || event.key === 'ArrowUp'
          ? index === 0
            ? lastStepIndex
            : index - 1
          : event.key === 'Home'
            ? 0
            : event.key === 'End'
              ? lastStepIndex
              : null

    if (nextIndex === null) return

    event.preventDefault()
    setActiveStep(nextIndex)
    stepTabRefs.current[nextIndex]?.focus()
  }

  async function handleSave() {
    saveFeedback.setPending()
    try {
      const result = await saveProposalEditor(payload)
      if (!result.ok) {
        if (result.version) setExpectedVersion(result.version)
        if (result.code === 'conflict') setConflictOpen(true)
        else saveFeedback.setError(result.error)
        return
      }
      setExpectedVersion(result.version)
      saveFeedback.setSuccess('Propuesta guardada')
      router.push(`/proposals/${id}`)
    } catch (error) {
      saveFeedback.setError(
        error instanceof Error ? error.message : 'No se pudo guardar la propuesta',
      )
    }
  }

  function handlePaymentScheduleChange(value: PaymentSchedule) {
    setField('paymentSchedule')(value)
    if (value !== 'custom') setField('paymentTerms')(PAYMENT_SCHEDULE_TEMPLATES[value])
    setField('paymentPlan')(paymentPlanForSchedule(value))
  }

  const handleGenerateDraft = useCallback(async () => {
    if (!leadId || generating || locked || !hasEmptyDraftFields) return
    setGenerating(true)
    aiFeedback.setPending()
    try {
      const res = await fetch(`/api/proposals/${id}/generate-draft`, { method: 'POST' })
      const json = await res.json()
      if (!res.ok) throw new Error(json.error ?? 'No se pudo preparar la propuesta.')

      const incoming = (json.pairs ?? []) as Array<Omit<EditablePair, 'id'>>
      const nextPairs = incoming.map((pair) => ({ ...createEmptyPair(), ...pair }))
      const nextScopeModules = (json.scope_modules ?? []) as ScopeModule[]
      const titleIsEmpty = !title.trim()
      const notesAreEmpty = !notes.trim()
      const contextIsEmpty = !contextMarkdown.trim()
      const pairsAreEmpty = pairs.length === 0
      const termsAreEmpty = !terms.trim()
      const modulesAreEmpty = scopeModules.length === 0
      const deliverablesAreEmpty = !deliverables.trim()
      const acceptanceCriteriaAreEmpty = !acceptanceCriteria.trim()
      const paymentTermsAreEmpty = !paymentTerms.trim()
      const changeManagementTermsAreEmpty = !changeManagementTerms.trim()
      if (titleIsEmpty) setField('title')(json.title)
      if (notesAreEmpty) setField('notes')(json.notes ?? '')
      if (contextIsEmpty) setField('contextMarkdown')(json.context_markdown ?? '')
      if (pairsAreEmpty) setField('pairs')(nextPairs)
      if (termsAreEmpty) setField('terms')(json.terms ?? '')
      if (modulesAreEmpty && nextScopeModules.length > 0) setField('scopeModules')(nextScopeModules)
      if (deliverablesAreEmpty) setField('deliverables')(json.deliverables ?? '')
      if (acceptanceCriteriaAreEmpty) setField('acceptanceCriteria')(json.acceptance_criteria ?? '')
      if (paymentTermsAreEmpty) {
        setField('paymentSchedule')(json.payment_schedule as PaymentSchedule)
        setField('paymentTerms')(json.payment_terms ?? '')
      }
      if (changeManagementTermsAreEmpty) {
        setField('changeManagementTerms')(json.change_management_terms ?? '')
      }
      aiFeedback.setSuccess('Borrador preparado con el contexto del lead')
    } catch (err) {
      aiFeedback.setError(err instanceof Error ? err.message : 'Error desconocido')
    } finally {
      setGenerating(false)
    }
  }, [
    acceptanceCriteria,
    aiFeedback,
    changeManagementTerms,
    contextMarkdown,
    deliverables,
    generating,
    hasEmptyDraftFields,
    id,
    leadId,
    locked,
    notes,
    pairs,
    paymentTerms,
    scopeModules,
    setField,
    terms,
    title,
  ])

  useEffect(() => {
    if (
      !autoGenerateDraft ||
      !aiEnabled ||
      !leadId ||
      locked ||
      !narrativeIsEmpty ||
      !commercialScopeIsEmpty ||
      automaticDraftStarted.current
    ) {
      return
    }
    automaticDraftStarted.current = true
    void handleGenerateDraft()
  }, [
    autoGenerateDraft,
    aiEnabled,
    leadId,
    locked,
    narrativeIsEmpty,
    commercialScopeIsEmpty,
    handleGenerateDraft,
  ])

  return (
    <>
      <div className="flex flex-col gap-5">
        {/* El CTA de guardar vive en la cabecera de la página (slot en page.tsx). */}
        {!locked && actionsSlot
          ? createPortal(
              <div className="flex items-center gap-2">
                <FormFeedback state={saveFeedback.state} pendingLabel="Guardando propuesta…" />
                <Button size="sm" onClick={() => void handleSave()} disabled={saveFeedback.pending}>
                  <Save aria-hidden />
                  {saveFeedback.pending ? 'Guardando…' : 'Guardar y ver propuesta'}
                </Button>
              </div>,
              actionsSlot,
            )
          : null}

        {saveFeedback.state.status === 'error' && saveErrors.length > 0 ? (
          <Alert variant="destructive" className="border-destructive/30 bg-destructive/5 px-4 py-3">
            <AlertCircle className="size-4" aria-hidden />
            <AlertTitle>No se ha podido guardar la propuesta</AlertTitle>
            <AlertDescription>
              <p>Revisa y corrige estos campos. Tus cambios siguen en esta pantalla.</p>
              <ul className="mt-2 list-disc space-y-1 pl-5">
                {saveErrors.map((error) => (
                  <li key={error}>{error}</li>
                ))}
              </ul>
            </AlertDescription>
          </Alert>
        ) : null}

        <nav aria-label="Pasos de la propuesta">
          <div
            role="tablist"
            aria-label="Secciones de la propuesta"
            className="flex gap-1 overflow-x-auto rounded-xl border border-border bg-card p-1 shadow-sm"
          >
            {EDITOR_STEPS.map((step, index) => {
              const active = activeStep === index
              return (
                <button
                  key={step.label}
                  ref={(element) => {
                    stepTabRefs.current[index] = element
                  }}
                  type="button"
                  onClick={() => setActiveStep(index)}
                  onKeyDown={(event) => handleStepKeyDown(event, index)}
                  role="tab"
                  id={`proposal-step-tab-${index}`}
                  aria-controls="proposal-editor-panel"
                  aria-selected={active}
                  aria-label={`Paso ${index + 1}: ${step.label}, ${stepComplete[index] ? 'completado' : 'pendiente'}`}
                  tabIndex={active ? 0 : -1}
                  className={`flex min-w-36 flex-1 items-center gap-2.5 rounded-lg px-3 py-2.5 text-left transition-colors focus-visible:ring-2 focus-visible:ring-ring focus-visible:outline-none sm:min-w-0 ${active ? 'bg-primary text-primary-foreground shadow-sm' : 'text-muted-foreground hover:bg-muted/70 hover:text-foreground'}`}
                >
                  <span
                    className={`flex size-6 shrink-0 items-center justify-center rounded-full text-[11px] font-semibold ${active ? 'bg-primary-foreground/20 text-primary-foreground' : stepComplete[index] ? 'bg-primary/10 text-primary' : 'bg-muted text-muted-foreground'}`}
                  >
                    {stepComplete[index] ? <Check className="size-3.5" aria-hidden /> : index + 1}
                  </span>
                  <span className="min-w-0">
                    <span className="block text-sm font-semibold">{step.label}</span>
                    <span
                      className={`hidden truncate text-[11px] sm:block ${active ? 'text-primary-foreground/75' : 'text-muted-foreground'}`}
                    >
                      {step.description}
                    </span>
                  </span>
                </button>
              )
            })}
          </div>
        </nav>

        <div className="grid items-start gap-5 xl:grid-cols-[minmax(0,1fr)_18rem]">
          <main
            id="proposal-editor-panel"
            role="tabpanel"
            aria-labelledby={`proposal-step-tab-${activeStep}`}
            tabIndex={-1}
            className="min-w-0"
          >
            {activeStep === 0 ? (
              <ProposalDetailsSection
                draft={draft}
                setField={setField}
                locked={locked}
                id={id}
                initialAttachments={initialAttachments}
                aiEnabled={aiEnabled}
                leadId={leadId}
                hasEmptyDraftFields={hasEmptyDraftFields}
                generating={generating}
                handleGenerateDraft={handleGenerateDraft}
                notesPreview={notesPreview}
                setNotesPreview={setNotesPreview}
              />
            ) : null}

            {activeStep === 1 ? (
              <ProposalScopeSection
                draft={draft}
                setField={setField}
                locked={locked}
                aiFeedback={aiFeedback}
                aiEnabled={aiEnabled}
                generating={generating}
                handleGenerateNarrative={handleGenerateNarrative}
              />
            ) : null}

            {activeStep === 2 ? (
              <ProposalPriceSection
                draft={draft}
                setField={setField}
                locked={locked}
                proposalTotals={proposalTotals}
                handleItemsChange={handleItemsChange}
                handlePaymentScheduleChange={handlePaymentScheduleChange}
              />
            ) : null}

            {activeStep === 3 ? (
              <ProposalReviewSection
                draft={draft}
                setField={setField}
                locked={locked}
                teamMembers={teamMembers}
                proposalTotals={proposalTotals}
                selectedMaintenance={selectedMaintenance}
              />
            ) : null}
          </main>

          <aside
            aria-label="Resumen comercial"
            className="flex flex-col gap-4 rounded-xl border border-border bg-card p-4 xl:sticky xl:top-24"
          >
            <div>
              <p className="text-xs font-medium tracking-wide text-muted-foreground uppercase">
                Resumen comercial
              </p>
              <p className="mt-1 text-sm text-muted-foreground">Se actualiza mientras editas.</p>
            </div>
            <div className="rounded-lg bg-muted/40 p-3">
              <p className="text-xs text-muted-foreground">Inversión inicial · IVA incluido</p>
              <p className="mt-1 text-2xl font-semibold tabular-nums">
                {formatEUR(proposalTotals.oneTime.total)}
              </p>
            </div>
            <div className="flex flex-col gap-2 text-sm">
              <div className="flex items-center justify-between gap-3">
                <span className="text-muted-foreground">Vigencia</span>
                <span className="font-medium">{validUntil || 'Pendiente'}</span>
              </div>
              {maintenanceOptions.enabled ? (
                <div className="flex items-center justify-between gap-3">
                  <span className="text-muted-foreground">Mantenimiento</span>
                  <span className="text-right font-medium">
                    {selectedMaintenance
                      ? `${formatEUR(selectedMaintenance.monthly_price)} / ${maintenanceOptions.billing_cycle === 'monthly' ? 'mes' : maintenanceOptions.billing_cycle === 'quarterly' ? 'trimestre' : 'año'}`
                      : 'Pendiente'}
                  </span>
                </div>
              ) : null}
              {proposalTotals.monthly.total > 0 ? (
                <div className="flex items-center justify-between gap-3">
                  <span className="text-muted-foreground">Recurrente en partidas</span>
                  <span className="font-medium tabular-nums">
                    {formatEUR(proposalTotals.monthly.total)}/mes
                  </span>
                </div>
              ) : null}
            </div>
            <div className="border-t border-border pt-3">
              <p className="mb-2 text-xs font-medium text-muted-foreground">Completitud</p>
              <div className="flex flex-col gap-2">
                {EDITOR_STEPS.map((step, index) => (
                  <div key={step.label} className="flex items-center gap-2 text-xs">
                    <Check
                      className={`size-3.5 ${stepComplete[index] ? 'text-primary' : 'text-muted-foreground/40'}`}
                      aria-hidden
                    />
                    <span
                      className={stepComplete[index] ? 'text-foreground' : 'text-muted-foreground'}
                    >
                      {step.label}
                    </span>
                  </div>
                ))}
              </div>
            </div>
          </aside>
        </div>

        <footer className="sticky bottom-3 z-20 flex items-center justify-between gap-3 rounded-xl border border-border bg-background/95 p-3 shadow-sm backdrop-blur">
          <p className="hidden min-w-0 text-sm text-muted-foreground sm:block">
            Paso {activeStep + 1} de {EDITOR_STEPS.length} ·{' '}
            <span className="font-medium text-foreground">{currentStep.label}</span>
          </p>
          <Button
            type="button"
            variant="outline"
            disabled={activeStep === 0}
            onClick={() => setActiveStep((step) => Math.max(0, step - 1))}
            className="flex-1 sm:ml-auto sm:flex-none"
          >
            <ChevronLeft className="size-4" aria-hidden />
            Anterior
          </Button>
          <Button
            type="button"
            disabled={activeStep === EDITOR_STEPS.length - 1 && (locked || saveFeedback.pending)}
            onClick={() => {
              if (activeStep === EDITOR_STEPS.length - 1) {
                void handleSave()
                return
              }
              setActiveStep((step) => Math.min(EDITOR_STEPS.length - 1, step + 1))
            }}
            className="flex-1 sm:flex-none"
          >
            {activeStep === EDITOR_STEPS.length - 1 ? (
              <>
                <Save className="size-4" aria-hidden />
                {saveFeedback.pending ? 'Guardando…' : 'Guardar y ver propuesta'}
              </>
            ) : (
              <>
                Continuar a {nextStep.label}
                <ChevronRight className="size-4" aria-hidden />
              </>
            )}
          </Button>
        </footer>
      </div>
      <VersionConflictDialog
        open={conflictOpen}
        entityName="propuesta"
        onKeepEditing={() => setConflictOpen(false)}
        onReload={() => {
          setConflictOpen(false)
          router.refresh()
        }}
      />
    </>
  )
}
