'use client'
import { useMemo, useState } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { formatEUR } from '@/lib/utils'
import type { CommandCenterMetrics } from '@/lib/finance/command-center'

export function CommandCenter({ metrics }: { metrics: CommandCenterMetrics }) {
  const [taxRate, setTaxRate] = useState(10), [target, setTarget] = useState(10000), [months, setMonths] = useState(6)
  const model = useMemo(() => { const gross = metrics.revenue - metrics.directCosts; const preTax = gross - metrics.fixedCosts; const avg = metrics.invoiceCount ? metrics.revenue / metrics.invoiceCount : 0; const cac = metrics.wonLeads ? metrics.adSpend / metrics.wonLeads : 0; const targetRevenue = (target / Math.max(.01, 1 - taxRate / 100) + metrics.fixedCosts) / Math.max(.01, 1 - metrics.directCosts / Math.max(metrics.revenue, 1)); return { gross, preTax, avg, cac, targetRevenue, monthly: targetRevenue / Math.max(1, months) } }, [metrics, taxRate, target, months])
  const eur = (v: number) => formatEUR(Math.round(v * 100) / 100)
  return <section className="flex flex-col gap-4" aria-labelledby="command-center-title"><div><h2 id="command-center-title" className="text-xl font-semibold tracking-tight">Centro de mando</h2><p className="text-muted-foreground mt-1 text-sm">Ingresos − costes directos = margen bruto; después estructura e impuestos estimados.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{[['Margen bruto', model.gross, 'Ingresos − costes directos'], ['Beneficio pre impuestos', model.preTax, 'Después de estructura'], ['Ticket medio', model.avg, `${metrics.invoiceCount} facturas`], ['CAC publicitario', model.cac, `${metrics.wonLeads} clientes ganados`]].map(([label, value, hint]) => <Card key={String(label)}><CardContent className="p-4"><p className="text-muted-foreground text-sm">{label}</p><p className="mt-2 text-2xl font-semibold tabular-nums">{eur(Number(value))}</p><p className="text-muted-foreground mt-1 text-xs">{hint}</p></CardContent></Card>)}</div><Card><CardHeader><CardTitle>Qué tenemos que facturar para conseguir {eur(target)} netos en {months} meses</CardTitle></CardHeader><CardContent className="grid gap-5 lg:grid-cols-[1fr_1fr]"><div className="grid gap-3 sm:grid-cols-3"><label className="text-sm">Impuesto estimado %<Input type="number" min="0" value={taxRate} onChange={e => setTaxRate(Number(e.target.value))} /></label><label className="text-sm">Beneficio neto objetivo<Input type="number" min="0" value={target} onChange={e => setTarget(Number(e.target.value))} /></label><label className="text-sm">Meses<Input type="number" min="1" value={months} onChange={e => setMonths(Number(e.target.value))} /></label></div><div className="bg-muted/40 rounded-lg p-4 text-sm"><p>Facturación total necesaria: <strong>{eur(model.targetRevenue)}</strong></p><p className="mt-1">Ritmo mensual: <strong>{eur(model.monthly)}</strong></p><p className="text-muted-foreground mt-3 text-xs">CAC = gasto Meta Ads / clientes ganados registrados. Si no hay atribución suficiente, es una señal pendiente, no un dato fiable.</p></div></CardContent></Card><p className="text-muted-foreground text-xs">Vista de gestión, no liquidación fiscal. Costes directos {eur(metrics.directCosts)} · estructura {eur(metrics.fixedCosts)} · horas {metrics.hours.toFixed(1)} h · Ads {eur(metrics.adSpend)}.</p></section>
}
