-- Only changes the default for new drafts. Issued and signed proposal terms
-- are intentionally preserved as contractual and evidentiary records.
alter table public.proposals
  alter column legal_terms set default $$1. **Contrato, partes y alcance.** La aceptación electrónica de esta propuesta, junto con sus anexos y condiciones particulares, formaliza el encargo entre Doscientos y el Cliente identificados en ella. Quien firma declara disponer de facultades suficientes para representar al Cliente. Solo están incluidos los trabajos y entregables descritos expresamente; cualquier cambio requerirá aceptación previa por escrito y, cuando proceda, presupuesto adicional.

2. **Vigencia, prelación y modificaciones.** La propuesta podrá aceptarse hasta la fecha de validez indicada. En caso de contradicción, prevalecerán por este orden: las condiciones particulares de la propuesta, sus anexos, estas condiciones generales y, por último, cualquier comunicación previa. Las modificaciones, aprobaciones, renuncias o ampliaciones de alcance solo serán válidas si constan por escrito en un canal de comunicación acordado.

3. **Precio, facturación y vencimientos.** Los importes, impuestos y calendario de pago son los indicados en esta propuesta. El Cliente abonará cada plazo en la fecha o al cumplirse el hito previsto. Si un plazo no tuviera fecha concreta, vencerá a los 30 días naturales de la recepción de la factura, salvo que una norma imperativa establezca otro cómputo. Entre empresas, ningún aplazamiento podrá superar el máximo legal aplicable.

4. **Mora, suspensión y resolución.** Desde el día siguiente al vencimiento, los importes impagados devengarán los intereses de demora y la compensación por costes de cobro previstos por la normativa aplicable; en operaciones comerciales, se aplicará la Ley 3/2004. Doscientos podrá, previo aviso escrito, suspender los trabajos, accesos, soporte y entregas mientras haya importes vencidos; los plazos se ampliarán en la misma medida. Si el impago persiste tras un requerimiento escrito que conceda un plazo razonable de subsanación, Doscientos podrá resolver el encargo y exigir los importes vencidos, el trabajo realizado y los compromisos no cancelables asumidos frente a terceros.

5. **Colaboración y control de cambios.** El Cliente facilitará en plazo los accesos, contenidos, decisiones y validaciones necesarios, y garantiza que dispone de los derechos necesarios sobre lo que entregue a Doscientos. Los plazos podrán ajustarse de forma proporcional ante retrasos, dependencias o decisiones imputables al Cliente o a terceros. Las solicitudes fuera de alcance se analizarán en coste, impacto y calendario antes de iniciarse.

6. **Entrega, correcciones y validación.** Doscientos comunicará la disponibilidad de cada entregable. El Cliente profesional deberá revisarlo frente a los criterios de aceptación pactados y comunicar por escrito, con detalle suficiente, las no conformidades verificables en un máximo de 10 días hábiles; dicho proceso no excederá de 30 días naturales. Doscientos corregirá las no conformidades reproducibles que se deban a un incumplimiento del alcance pactado. Las observaciones ajenas al alcance, los cambios de preferencia o la decisión de no utilizar el entregable no constituyen una no conformidad ni suspenden el pago. La puesta en producción o uso efectivo del entregable supondrá su aceptación. Los derechos imperativos de consumidores y usuarios no quedan limitados por esta cláusula.

7. **Soporte, disponibilidad y terceros.** Salvo que la propuesta establezca expresamente un servicio de mantenimiento o nivel de servicio, la entrega no incluye soporte continuado, evolución, alojamiento, copias de seguridad ni disponibilidad garantizada. Los servicios, licencias, plataformas, APIs y materiales de terceros se sujetan a sus propios términos, disponibilidad y precios; Doscientos no responde de cambios, interrupciones o retiradas imputables a dichos terceros, sin perjuicio de colaborar razonablemente en su diagnóstico.

8. **Cancelación por el Cliente.** El Cliente podrá solicitar la terminación anticipada por escrito. En ese caso se liquidarán el trabajo efectivamente realizado y documentado hasta la fecha, los gastos de terceros no cancelables y los costes razonables e inevitables de recursos ya reservados que no puedan reasignarse. Los importes ya pagados se imputarán a esa liquidación y se devolverá cualquier exceso que resulte a favor del Cliente. Tras una entrega conforme, la decisión posterior de no continuar, no publicar o no utilizar el trabajo no libera al Cliente del pago de los importes devengados.

9. **Propiedad intelectual.** Una vez abonado íntegramente el precio, Doscientos cede al Cliente los derechos de explotación necesarios sobre los desarrollos creados específicamente para este proyecto —reproducción, distribución, comunicación pública y transformación— para cualquier territorio y durante el máximo plazo legal. Quedan excluidos y seguirán siendo titularidad de Doscientos sus herramientas, bibliotecas, plantillas, componentes genéricos, metodologías, conocimientos previos y mejoras reutilizables, que Doscientos podrá usar y adaptar en otros proyectos, sin revelar información confidencial del Cliente. Los componentes de terceros se regirán por sus propias licencias.

10. **Confidencialidad, datos y evidencia de firma.** Cada parte protegerá la información confidencial de la otra y solo la usará para ejecutar este encargo. Si Doscientos trata datos personales por cuenta del Cliente, las partes formalizarán, cuando sea exigible, el correspondiente acuerdo de encargo de tratamiento antes de dicho acceso. Doscientos tratará los datos de contacto y la evidencia de aceptación como responsable para gestionar la relación contractual, acreditar el consentimiento y atender obligaciones legales, durante la relación y los plazos de conservación o prescripción aplicables.

11. **Subcontratación.** Doscientos podrá recurrir a profesionales o proveedores cualificados para ejecutar el encargo, permaneciendo responsable de la coordinación de sus prestaciones y exigiéndoles obligaciones de confidencialidad y protección de datos acordes con el servicio.

12. **Fuerza mayor.** Ninguna parte responderá por retrasos o incumplimientos causados por hechos fuera de su control razonable, incluidos fallos generales de proveedores, ciberincidentes no imputables, conflictos laborales, desastres naturales o actuaciones de autoridades. La parte afectada avisará sin demora razonable y ambas cooperarán para reducir el impacto; si la situación se prolonga de forma sustancial, cualquiera podrá resolver las prestaciones pendientes sin perjuicio de los importes ya devengados.

13. **Caso de éxito.** Salvo pacto escrito distinto, el Cliente autoriza a Doscientos a describir la colaboración como caso de éxito y a mostrar los entregables ya hechos públicos, su denominación, marcas y logotipos, exclusivamente para acreditar su experiencia profesional. Doscientos no divulgará información confidencial, datos personales ni métricas no públicas, y atenderá las objeciones razonables y justificadas del Cliente cuando exista un riesgo legítimo para su seguridad, sus secretos empresariales o el cumplimiento normativo.

14. **Responsabilidad.** Salvo norma imperativa aplicable, dolo, culpa grave o responsabilidad que legalmente no pueda excluirse, la responsabilidad total de Doscientos se limitará al importe efectivamente abonado por el Cliente por el servicio que origine la reclamación. En relaciones entre empresas, Doscientos no responderá por lucro cesante, pérdida de negocio, pérdida de datos, daños indirectos o perjuicios consecuenciales que no fueran previsibles de forma razonable al contratar.

15. **Comunicaciones, cesión y separabilidad.** Las comunicaciones operativas y las notificaciones se realizarán por los correos electrónicos y canales indicados en la propuesta o posteriormente acordados por escrito. El Cliente no podrá ceder el encargo sin autorización previa de Doscientos; Doscientos podrá cederlo a una entidad sucesora o vinculada que asuma estas obligaciones, informando al Cliente cuando resulte exigible. La nulidad de una cláusula no afectará a las restantes, que conservarán su eficacia. La tolerancia o falta de ejercicio de un derecho no supone renuncia a él.

16. **Ley aplicable y consumidores.** Para relaciones entre empresas, las partes se someten a la legislación española y a los juzgados y tribunales de Barcelona. Si el Cliente actúa como consumidor, se aplicarán la información precontractual, derechos de desistimiento, garantías y fueros imperativos que correspondan; cualquier inicio anticipado de servicios o contenido digital requerirá las solicitudes y consentimientos expresos legalmente exigibles.$$;